<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns="http://publications.europa.eu/ns/"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl" 
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    exclude-result-prefixes="xd xsl fn"
    version="3.0">

    <xsl:import href="../../config-proxy.xsl"/>
    <xsl:output version="1.0" encoding="UTF-8" indent="yes" /> 

    <xsl:param name="corePath" as="xs:string?"/>
    <xsl:param name="restrictionsPath" as="xs:string?"/>
    
    <xd:doc>
        <xd:desc>
            A template for generating catalog XML file that specification of
            sources to be imported by a Robot or Protege during processing an
            ontology file generated by model2owl. The catalog file is needed for
            Robot to correctly resolve internal and external imports. This is a
            temporary workaround and it's needed because both ePO and ADMS
            published versions are faulty/invalid.
        </xd:desc>
    </xd:doc>
    <xsl:template match="/">
        <catalog prefer="public" xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
            <xsl:if test="exists($corePath)">
                <uri id="User Entered Import Resolution" name="{$coreArtefactURI}" uri="{$corePath}"/>
            </xsl:if>
            <xsl:if test="exists($restrictionsPath)">
                <uri id="User Entered Import Resolution" name="{$restrictionsArtefactURI}" uri="{$restrictionsPath}"/>
            </xsl:if>
            <!-- temporary workaround, see https://github.com/SEMICeu/ADMS/issues/15 -->
            <uri id="User Entered Import Resolution" name="http://www.w3.org/ns/adms" uri="https://raw.githubusercontent.com/SEMICeu/ADMS/refs/heads/main/releases/2.00/voc/adms.ttl"/>
            <group id="Folder Repository, directory=, recursive=true, Auto-Update=true, version=2" prefer="public" xml:base=""/>
        </catalog>
</xsl:template>
</xsl:stylesheet>
